# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"

# Redirect rules
[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

# Build hooks - can be triggered by Contentful webhooks
[build.environment]
  NODE_VERSION = "18.19.0"
  # VITE_CONTENTFUL_SPACE_ID - Set in Netlify UI
  # VITE_CONTENTFUL_ACCESS_TOKEN - Set in Netlify UI
  # VITE_CONTENTFUL_PREVIEW_TOKEN - Set in Netlify UI
  # VITE_CONTENTFUL_ENVIRONMENT - Set in Netlify UI
  CONTENTFUL_REBUILD_HOOK = "https://api.netlify.com/build_hooks/67d782602c666be1d13a74e5"

# Build optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Edge function for blog metadata - special handling for social media crawlers
[[edge_functions]]
  path = "/blog/*"
  function = "social-metadata"

# Edge function for tools metadata
[[edge_functions]]
  path = "/tools"
  function = "social-metadata"

[[edge_functions]]
  path = "/tools/*"
  function = "social-metadata"

# Debug tool for social sharing metadata
[[edge_functions]]
  path = "/debug-social"
  function = "debug-social"

# Cache control headers for blog pages - ensure latest metadata
[[headers]]
  for = "/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=60, s-maxage=300"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[dev]
  framework = "vite"