# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"

# Regular redirect rules
[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

# Specific redirect for sitemap.xml to ensure it's always accessible
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# Build hooks - can be triggered by Contentful webhooks
[build.environment]
  NODE_VERSION = "18.19.0"
  # Contentful environment variables - hardcoded for now, should be moved to Netlify UI when possible
  VITE_CONTENTFUL_SPACE_ID = "hdo1k8om3hmw"
  VITE_CONTENTFUL_ACCESS_TOKEN = "g29C2epdpHoOQsex08PJXphQYxqVWsN-cUZBbO9QA4A"
  VITE_CONTENTFUL_PREVIEW_TOKEN = "81cfBHWQVwo4pe7ZPisFfvJrzpwCy-AHyBEuf_DA5tQ"
  VITE_CONTENTFUL_ENVIRONMENT = "master"
  CONTENTFUL_REBUILD_HOOK = "https://api.netlify.com/build_hooks/67d782602c666be1d13a74e5"
  PRERENDER_TOKEN = "DXHxiXW4lVGsLvOASJvj"

# Build optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Increase timeouts for edge functions to handle prerender.io
[functions]
  node_bundler = "esbuild"
  
[functions.edge]
  # Increase edge function timeouts to prevent timeout issues with prerender
  external_node_modules = ["@netlify/edge-functions"]
  # Increase the timeout to 10 seconds
  included_files = ["netlify/edge-functions/*"]

# Prerender middleware that runs before other edge functions
[[edge_functions]]
  path = "/*"
  function = "prerender-middleware"

# Edge function for blog metadata - special handling for social media crawlers
[[edge_functions]]
  path = "/blog/*"
  function = "social-metadata"

# Edge function for tools metadata
[[edge_functions]]
  path = "/tools"
  function = "social-metadata"

[[edge_functions]]
  path = "/tools/*"
  function = "social-metadata"

# Debug tool for social sharing metadata
[[edge_functions]]
  path = "/debug-social"
  function = "debug-social"

# Cache control headers for blog pages - ensure latest metadata
[[headers]]
  for = "/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=60, s-maxage=300"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Special header for sitemap.xml to ensure it's properly served
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "noarchive"

# Optimize prerendering by caching common static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  framework = "vite"